sudo: required
services: 
  - docker

before_install:
  - docker build -t knowge/docker-react -f Dockerfile.dev .

script: 
  - docker run knowge/docker-react npm run test -- --coverage

deploy:
  provider: elacticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-473630069835"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
